"""
watchkey/core.py
Encrypt and decrypt a Bitcoin seed phrase using biometric entropy
collected from an Apple Watch (heart rate + accelerometer samples).
"""

import hashlib
import hmac
import json
import os
import struct
import time
from dataclasses import dataclass, asdict
from typing import List, Optional

from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes


# ── Biometric sample ──────────────────────────────────────────────────────────

@dataclass
class BiometricSample:
    """One snapshot from the Apple Watch sensors."""
        timestamp: float          # Unix epoch (seconds)
            heart_rate_bpm: float     # BPM reported by optical sensor
                accel_x: float            # m/s²
                    accel_y: float
                        accel_z: float
                            gyro_x: float             # rad/s
                                gyro_y: float
                                    gyro_z: float

                                        def to_bytes(self) -> bytes:
                                                """Deterministic binary representation for entropy extraction."""
                                                        return struct.pack(
                                                                    ">8d",
                                                                                self.timestamp,
                                                                                            self.heart_rate_bpm,
                                                                                                        self.accel_x, self.accel_y, self.accel_z,
                                                                                                                    self.gyro_x,  self.gyro_y,  self.gyro_z,
                                                                                                                            )


                                                                                                                            # ── Entropy extraction ────────────────────────────────────────────────────────

                                                                                                                            def extract_entropy(samples: List[BiometricSample], salt: bytes) -> bytes:
                                                                                                                                """
                                                                                                                                    Derive a 32-byte entropy value from a list of biometric samples.

                                                                                                                                        We feed every sample's raw bytes into an HMAC-SHA256 chain
                                                                                                                                            (salt → sample₀ → sample₁ → … → sampleₙ), then run the
                                                                                                                                                result through PBKDF2 to slow down brute-force attempts.
                                                                                                                                                    """
                                                                                                                                                        if len(samples) < 10:
                                                                                                                                                                raise ValueError("Provide at least 10 biometric samples for adequate entropy.")

                                                                                                                                                                    # HMAC chain over all samples
                                                                                                                                                                        chain = salt
                                                                                                                                                                            for s in samples:
                                                                                                                                                                                    chain = hmac.new(chain, s.to_bytes(), hashlib.sha256).digest()

                                                                                                                                                                                        # Stretch with PBKDF2 (310 000 rounds — NIST 2023 recommendation)
                                                                                                                                                                                            kdf = PBKDF2HMAC(
                                                                                                                                                                                                    algorithm=hashes.SHA256(),
                                                                                                                                                                                                            length=32,
                                                                                                                                                                                                                    salt=salt,
                                                                                                                                                                                                                            iterations=310_000,
                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                    return kdf.derive(chain)


                                                                                                                                                                                                                                    # ── Encrypt / Decrypt ─────────────────────────────────────────────────────────

                                                                                                                                                                                                                                    def encrypt_seed(seed_phrase: str, samples: List[BiometricSample]) -> dict:
                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                            Encrypt *seed_phrase* with a key derived from *samples*.

                                                                                                                                                                                                                                                Returns a JSON-serialisable dict that should be saved to disk.
                                                                                                                                                                                                                                                    The dict contains everything needed for decryption EXCEPT the
                                                                                                                                                                                                                                                        biometric data — that must come from the user's wrist at runtime.
                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                salt = os.urandom(32)
                                                                                                                                                                                                                                                                    key  = extract_entropy(samples, salt)
                                                                                                                                                                                                                                                                        nonce = os.urandom(12)

                                                                                                                                                                                                                                                                            aesgcm = AESGCM(key)
                                                                                                                                                                                                                                                                                ciphertext = aesgcm.encrypt(nonce, seed_phrase.encode(), None)

                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                            "version": 1,
                                                                                                                                                                                                                                                                                                    "created_at": time.time(),
                                                                                                                                                                                                                                                                                                            "salt": salt.hex(),
                                                                                                                                                                                                                                                                                                                    "nonce": nonce.hex(),
                                                                                                                                                                                                                                                                                                                            "ciphertext": ciphertext.hex(),
                                                                                                                                                                                                                                                                                                                                    "sample_count": len(samples),
                                                                                                                                                                                                                                                                                                                                        }


                                                                                                                                                                                                                                                                                                                                        def decrypt_seed(vault: dict, samples: List[BiometricSample]) -> str:
                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                Decrypt a vault dict produced by *encrypt_seed* using fresh
                                                                                                                                                                                                                                                                                                                                                    biometric samples from the Apple Watch.

                                                                                                                                                                                                                                                                                                                                                        Raises ValueError if decryption fails (wrong biometrics / tampered vault).
                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                salt       = bytes.fromhex(vault["salt"])
                                                                                                                                                                                                                                                                                                                                                                    nonce      = bytes.fromhex(vault["nonce"])
                                                                                                                                                                                                                                                                                                                                                                        ciphertext = bytes.fromhex(vault["ciphertext"])

                                                                                                                                                                                                                                                                                                                                                                            key = extract_entropy(samples, salt)
                                                                                                                                                                                                                                                                                                                                                                                aesgcm = AESGCM(key)

                                                                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                                                            plaintext = aesgcm.decrypt(nonce, ciphertext, None)
                                                                                                                                                                                                                                                                                                                                                                                                except Exception:
                                                                                                                                                                                                                                                                                                                                                                                                        raise ValueError(
                                                                                                                                                                                                                                                                                                                                                                                                                    "Decryption failed — biometric samples do not match the vault. "
                                                                                                                                                                                                                                                                                                                                                                                                                                "Make sure you are wearing the same Apple Watch and try again."
                                                                                                                                                                                                                                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                                                                                                                                                                                                                            return plaintext.decode()


                                                                                                                                                                                                                                                                                                                                                                                                                                            # ── Vault I/O ─────────────────────────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                                            def save_vault(vault: dict, path: str) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                with open(path, "w") as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                        json.dump(vault, f, indent=2)


                                                                                                                                                                                                                                                                                                                                                                                                                                                        def load_vault(path: str) -> dict:
                                                                                                                                                                                                                                                                                                                                                                                                                                                            with open(path) as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return json.load(f)"""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    watchkey/core.py
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Encrypt and decrypt a Bitcoin seed phrase using biometric entropy
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    collected from an Apple Watch (heart rate + accelerometer samples).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    import hashlib
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    import hmac
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    import json
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    import os
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    import struct
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    import time
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    from dataclasses import dataclass, asdict
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    from typing import List, Optional

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    from cryptography.hazmat.primitives import hashes


                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # ── Biometric sample ──────────────────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @dataclass
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    class BiometricSample:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """One snapshot from the Apple Watch sensors."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            timestamp: float          # Unix epoch (seconds)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                heart_rate_bpm: float     # BPM reported by optical sensor
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    accel_x: float            # m/s²
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        accel_y: float
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            accel_z: float
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gyro_x: float             # rad/s
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gyro_y: float
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        gyro_z: float

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def to_bytes(self) -> bytes:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Deterministic binary representation for entropy extraction."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return struct.pack(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ">8d",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    self.timestamp,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.heart_rate_bpm,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.accel_x, self.accel_y, self.accel_z,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self.gyro_x,  self.gyro_y,  self.gyro_z,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ── Entropy extraction ────────────────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def extract_entropy(samples: List[BiometricSample], salt: bytes) -> bytes:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Derive a 32-byte entropy value from a list of biometric samples.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            We feed every sample's raw bytes into an HMAC-SHA256 chain
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (salt → sample₀ → sample₁ → … → sampleₙ), then run the
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    result through PBKDF2 to slow down brute-force attempts.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if len(samples) < 10:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    raise ValueError("Provide at least 10 biometric samples for adequate entropy.")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # HMAC chain over all samples
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            chain = salt
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for s in samples:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        chain = hmac.new(chain, s.to_bytes(), hashlib.sha256).digest()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Stretch with PBKDF2 (310 000 rounds — NIST 2023 recommendation)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                kdf = PBKDF2HMAC(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        algorithm=hashes.SHA256(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                length=32,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        salt=salt,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                iterations=310_000,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return kdf.derive(chain)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # ── Encrypt / Decrypt ─────────────────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def encrypt_seed(seed_phrase: str, samples: List[BiometricSample]) -> dict:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Encrypt *seed_phrase* with a key derived from *samples*.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Returns a JSON-serialisable dict that should be saved to disk.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        The dict contains everything needed for decryption EXCEPT the
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            biometric data — that must come from the user's wrist at runtime.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    salt = os.urandom(32)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        key  = extract_entropy(samples, salt)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            nonce = os.urandom(12)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                aesgcm = AESGCM(key)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ciphertext = aesgcm.encrypt(nonce, seed_phrase.encode(), None)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "version": 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "created_at": time.time(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "salt": salt.hex(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "nonce": nonce.hex(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "ciphertext": ciphertext.hex(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "sample_count": len(samples),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def decrypt_seed(vault: dict, samples: List[BiometricSample]) -> str:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Decrypt a vault dict produced by *encrypt_seed* using fresh
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        biometric samples from the Apple Watch.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Raises ValueError if decryption fails (wrong biometrics / tampered vault).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    salt       = bytes.fromhex(vault["salt"])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        nonce      = bytes.fromhex(vault["nonce"])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ciphertext = bytes.fromhex(vault["ciphertext"])

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                key = extract_entropy(samples, salt)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    aesgcm = AESGCM(key)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                plaintext = aesgcm.decrypt(nonce, ciphertext, None)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            raise ValueError(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Decryption failed — biometric samples do not match the vault. "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Make sure you are wearing the same Apple Watch and try again."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return plaintext.decode()


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ── Vault I/O ─────────────────────────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def save_vault(vault: dict, path: str) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    with open(path, "w") as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            json.dump(vault, f, indent=2)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def load_vault(path: str) -> dict:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with open(path) as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return json.load(f)